---
title: "egg-snow"
format: html
---


```{r, message=FALSE}
library(tidyverse)
library(RColorBrewer)
```


## Define path and filenames

```{r}
path_raw <- "data/raw"

sites_csv <- "site.csv"

snowcover_csv <- "snow_cover.csv"

nests_csv <- "ASDN_Bird_nests.csv"

eggs_csv <- "ASDN_Bird_eggs.csv"

lemmings_csv <- "ASDN_Daily_pred_lemm.csv"

species_csv <- "species.csv"

```

## Import data

```{r}

sites_data <- read_csv(file.path(path_raw, sites_csv))

snowcover_data <- read_csv(file.path(path_raw, snowcover_csv))

nests_data <- read_csv(file.path(path_raw, nests_csv))

eggs_data <- read_csv(file.path(path_raw, eggs_csv))

lemmings_data <- read_csv(file.path(path_raw, lemmings_csv))

species_data <- read_csv(file.path(path_raw, species_csv))

```

## Summarize the nests table

```{r}
nests_sum <- nests_data %>%
  group_by(Site, Year, Species) %>%
  summarize(n_nest = n())
```

## Summarize the snow cover table

```{r}
# adding the snow days with a threshold at 10%
snowcover_data <- snowcover_data %>%
  mutate(snow_days = ifelse(Snow_cover > 10, 1, 0))


snow_sum <- snowcover_data %>%
  group_by(Site, Year) %>%
  summarise(cum_snow_days = sum(snow_days, na.rm=TRUE))
```

 
## Join the two

```{r}
nest_snow <- nests_sum %>%
  inner_join(snow_sum, join_by(Site, Year))

names(nest_snow)
```

```{r}
ggplot(nest_snow, aes(x=cum_snow_days, y=n_nest , color=Species)) + 
  geom_point() +
  scale_colour_brewer(palette = "Set3") +
  facet_wrap(vars(Site), scales = "free")
```

```{r}
lemming_sum <- lemmings_data %>%
  group_by(Site, Year, Species) %>%
  summarize(n_lemmings = n())
```



```{r}
nest_lemm <- nests_sum %>%
  inner_join(lemming_sum, join_by(Site, Year))

names(nest_lemm)
```



```{r}
ggplot(nest_lemm, aes(x=n_lemmings, y=n_nest , color=Species.x)) + 
  geom_point()
```

## Which species makes the most eggs

```{r}
eggs_sum <- eggs_data %>%
  group_by(Site, Year, Nest_ID) %>%
  summarize(n_egg = max(Egg_num)) %>%
  ungroup()
```


```{r}
nest_species <- eggs_sum %>%
  left_join(nests_data, join_by(Site, Year, Nest_ID))
```


```{r}
nest_species_avg <- nest_species %>%
  group_by(Species) %>%
  summarise(avg_egg_numb = mean(n_egg))

nest_species_avg %>%
  arrange(desc(avg_egg_numb))
```

```{r}
nest_species_avg <- nest_species_avg %>%
  left_join(species_data, join_by(Species==Code))
```


```{r}
nest_species_avg %>% 
  select(-Relevance) %>%
  relocate(avg_egg_numb, .after = last_col()) %>%
  arrange(desc(avg_egg_numb))
```

